### ISSUE TITLE
Refactor Tests and CI

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#102]
Create two seperate test suites, one quick test suite that will always run and one with long tests that only run when we want to create a draft release. Also only run coverage for releases.

Examples for current long tests: "test_sentiment_classifier.py"

### Tasks

- [x] Coverage only for releases
- [ ] Long Tests for Longer tests only for releases
- [ ] Normal Tests as usual.

**Comment by mmschlk** [comment]
Alternativly, we can chache folders like the language model download folder in the tests similarly to the pip packages.

River does it as such: https://github.com/online-ml/river/blob/main/.github/workflows/unit-tests.yml

**Comment by mmschlk** [comment]
https://pypi.org/project/pytest-skip-slow/
