### ISSUE TITLE
Add SVARM based approximatord

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#32]
Add the SVARM based SV and CII approximators. The estimators should work with any sampling strategies.

### Tasks
- [ ] add SVARM-IQ estimator for CII
- [ ] make SVARM-IQ behave as SVARM for SV
- [ ] add documentation
- [ ] make SVARM-IQ (and SVARM) be able to use the improved sampling procedure as defined in #30
