### ISSUE TITLE
Add shap Plots to shapiq

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#34]
## Description
The `InteractionValues` dataclass is the core data object containing the results and of approximators and explainers. For representing Shapley values (SVs) visually, the _shap_ package already contains a plethora of very helpful illustration techniques. To ease new users into the package and increase the functionality of _shapiq_, we should also offer the most important plots for the SV or, if possible, even for Shapley interactions (SIs).

In `shap`, there are two kinds of plots which should be integrated somewhat like the following:
- **One Explanation:** Some plots illustrate **one** `shap.Explanation` at a time. This should be possible to recreate in our codebase with **one InteractionValues** object. 
- **Multiple Explanations:** Other plots capture **multiple** `shap.Explanations` at a time. This should be possible with a **list of InteractionValues** objects.

## Plot Descriptons
You can see the plots in the [readme](https://github.com/shap/shap/blob/master/README.md) of the main shap repo.

### Force Plot
The force plot shows how each feature attribution or interaction **pulls** and **pushes** the prediction from the **empty prediction / baseline** $\nu(\emptyset)$ towards the prediction with all features / grand coalition $\nu(N)$. This plot works only for a single explanation:

![image](https://github.com/mmschlk/shapiq/assets/45100845/038da008-ea50-40bf-bd7b-5054e0d4465f)

### Waterfall Plot
The waterfall plot disentangles the attributions presented in the force plot but shows basically the same information. Notably, it prints only the top-X attributions. This plot works only for a single explanation:

![image](https://github.com/mmschlk/shapiq/assets/45100845/a071ec9b-9ba3-4f53-b245-114d321c0341)

### Bar Plot
The bar plot shows the mean absolute value of the attribution/interactions wich can be used as a proxy for feature importance. This plot works only for multiple explanations:

![image](https://github.com/mmschlk/shapiq/assets/45100845/35d677fe-74c7-4faa-94b8-4ae6f7055979)

## How To:
For this we need to port the `shap` plots to `shapiq` and potentially extend the dataclass.
- We will need to add the feature values of `x_explain` to each `InteractionValues` object as some plots require information about the feature names and the feature values.
- We will not port 100% functionality from the `shap` plots to `shapiq` but the main ones.

## Tasks:
- [x] Add the [waterfall plot](https://github.com/shap/shap/blob/master/shap/plots/_waterfall.py) like used in [the original TreeSHAP-IQ implementation](https://github.com/mmschlk/TreeSHAP-IQ/blob/db4fe9b52119c1977645be18fd8ac06c270ee4df/experiment_main.py#L216C1-L267C51) for _SV_ **and** _SI_.
- [x] Add the [force plot](https://github.com/shap/shap/blob/master/shap/plots/_force_matplotlib.py) like used in [the original TreeSHAP-IQ implementation](https://github.com/mmschlk/TreeSHAP-IQ/blob/db4fe9b52119c1977645be18fd8ac06c270ee4df/experiment_main.py#L269C1-L293C51) for _SV_ **and** _SI_
- [x] Add the [bar plot](https://github.com/shap/shap/blob/master/shap/plots/_bar.py) for _SV_ **and** _SI_. For _SI_, the plot can just treat every item as a feature.
- [x] Add tests with 100% coverage for these plots

**Comment by hbaniecki** [comment]
comment on beeswarm: not clear how to indicate "feature value" for interactions

**Comment by mmschlk** [comment]
Removing beeswarm and scatter plot as it is not so clear what the "feature value" of a interaction should be for plotting. Waterfall still makes sense.
