### ISSUE TITLE
Fix Naming for Interaction Scores

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#37]
Fix a naming convention for the interaction indices / scores used. Most importantly, fix how to call the interaction index described in [this work](https://proceedings.mlr.press/v206/bordt23a). 

Candidates are (may be extended): nSII, n-SII, nShapley, kSII, k-SII, kShapley.

### Tasks
- [x] Decide on names and abbreviations.
- [x] Make all changes to reflect the new name in the code-base (change all interaction indices names in the code base which is usually used under available indices among other places or class names).
- [x]  Change the documentation accordingly.

**Comment by kolpaczki** [comment]
I would go with something that uses 'k' instead of 'n', as n is commonly known as the player number in cooperative games.

**Comment by mmschlk** [comment]
Decision: when we talk about the k-additive aggregation of the SII, we will talk about `k-SII` (and `k_SII` where applicable) **in the code**. The abbreviation can be in papers: _"$k$-SII"_ with the math environment around the "k". When speaking to users' i.e. by not resorting to the technical term we will call it `k-Shapley Interactions`.
