### ISSUE TITLE
Add a "Collaborate" tutorial to the repo

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#39]
Add a readme/markdown/info file to onboard new collaborators to the repository.

### Tasks
- [ ] Brainstorm what is important for a new collaborator to have.
- [ ] Write "Collaborate" File and add to repo
- [ ] Test the file with a new user to the repo and incorporate the feedback from the process to the file.
