### ISSUE TITLE
Add Conditional Feature Removal (Tabular)

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#40]
Next to interventional approaches also observational explanations should be created with shapiq. For this conditional modelling and sampling of and from the tabular data distributions is required. This [arfpy package](https://arxiv.org/abs/2311.07366) should do the job.

### Tasks
- [ ] Implement Conditional Feature Removal (imputer) for tabular data: Potenitally with [arfpy](https://arxiv.org/abs/2311.07366).
- [ ] Make this technique available for the tabular explainer
- [ ] Create tests for the conditional imputer and explainer variants
- [ ] Add documentation to the imputer with the correct links and citations
- [ ] Add Jupyter notebook example that are visible in the documentation (visibility can be handled independently in #38)

**Comment by hbaniecki** [comment]
look at https://link.springer.com/article/10.1007/s10618-024-01016-z
