### ISSUE TITLE
Benchmark Games?

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#63]
Since one target audience of shapiq are game theory, ML, and XAI researchers it would be neat to provide benchmark "datasets"/games to test the approximators on. 

I don't know weather this is feature creep or in scope, but I feel like this is in scope. 

We already have lots of games for which a stronger API would be cool.

I see a couple of arguments why we should add a collection of games.
- It can show novice users and researchers how easy it is to frame their abstract problem as a cooperative game and compute some Shapley Interactions from this.
- We can easily run benchmarks and check the performance of all our approximators "in-house" (this might be required for certain venues where a paper can be submitted to).
- Testing is easier.

## Tasks
- [x] Discuss if this should be done.
- [x] If yes, research and list what games we want to incorporate.
- [x] If yes, plan a games API (base game class)
- [x] Create seperate issues for the games API and individual games to incorporate.

**Comment by mmschlk** [comment]
Yes we will add bencharks

**Comment by mmschlk** [comment]
We will start with the following list of „benchmark games“ and datasets.

- SOUM (synthetic)
- IMDB Sentiment Prediction Model (DistilBERT)
- Imagenet classifier (Vision Transformer)
- Imagenet classifier (CNN + Superpixels)
- California Housing Regression + Model
- Bike Rental Regression + Model
- Adult Census Classification + Model

**Comment by mmschlk** [comment]
issues created:
