### ISSUE TITLE
Add Tabular Game with example datasets

### ISSUE THREAD

**Issue by mmschlk** [mmschlk/shapiq#80]
Add the Tabular Machine Learning as a local Game with a couple of datasets as ready-to-use examples. There, if possible, make use of the imputer.

# Tasks
- [x] Add FeatureSelection Game
- [x] Add local XAI Game for tabular models
- [ ] Create instanitiations of these games, precompute and store them

**Comment by mmschlk** [comment]
Started work on this in #92
